apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadjrrb5899-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadjrrb5899-tenant-component
    app.kubernetes.io/part-of: loadjrrb5899-tenant-app
  name: loadjrrb5899-tenant-component
  namespace: loadjrrb5899-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadjrrb5899-tenant-component
    weight: null
status: {}
